"""Posting reviews to GitHub with idempotency.

The idempotency marker is an invisible HTML comment carrying a deterministic
run key of ``repo#number@head_sha``: re-running on an unchanged PR is a
no-op, while a new push (new head SHA) permits a fresh review. Only markers
in reviews authored by the bot token's own identity count — a copied marker
string in someone else's comment cannot suppress a review.
"""

from __future__ import annotations

from collections.abc import Sequence

from pr_review_agent.github.models import Review, ReviewCommentDraft
from pr_review_agent.review.models import AgentComment

MARKER_PREFIX = "pr-review-agent"


def run_key(repo: str, number: int, head_sha: str) -> str:
    return f"{repo}#{number}@{head_sha}"


def marker(key: str) -> str:
    return f"<!-- {MARKER_PREFIX}:{key} -->"


def find_existing_review(reviews: Sequence[Review], key: str, bot_login: str) -> Review | None:
    """The bot's own review carrying this run key, if one exists."""
    mark = marker(key)
    for review in reviews:
        if review.author == bot_login and mark in review.body:
            return review
    return None


def review_body(key: str, comments: Sequence[AgentComment]) -> str:
    return (
        f"Automated review · {len(comments)} comment(s) · generated by {MARKER_PREFIX}.\n"
        f"\n{marker(key)}"
    )


def to_draft_comments(comments: Sequence[AgentComment]) -> list[ReviewCommentDraft]:
    return [
        ReviewCommentDraft(path=c.file_path, line=c.line, body=_format_comment(c)) for c in comments
    ]


def _format_comment(comment: AgentComment) -> str:
    return (
        f"{comment.body}\n\n"
        f"_severity: {comment.severity.value} · confidence: {comment.confidence:.2f}"
        f" · category: {comment.category}_"
    )
